# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'musicGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import playsound
from threading import Thread
import scipy
import math
from PyQt5 import QtCore, QtGui, QtWidgets,QtMultimedia
from PyQt5.QtMultimedia import QMediaPlayer
from PyQt5.QtGui import QPixmap
from pyqtgraph import PlotWidget
from scipy.io import wavfile
from scipy.fft import fft, fftfreq,ifft
import matplotlib.pyplot as plt
import numpy as np
import wave
import contextlib
from PyQt5.QtWidgets import QFileDialog , QLabel
import pyqtgraph as pg
import sounddevice as sd
from PyQt5.QtMultimedia import QMediaPlayer, QMediaContent

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.mw = MainWindow
        MainWindow.resize(1645, 1061)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 1581, 1021))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pause_button = QtWidgets.QPushButton(self.tab)
        self.pause_button.setGeometry(QtCore.QRect(210, 70, 31, 31))
        self.pause_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pause.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_button.setIcon(icon)
        self.pause_button.setObjectName("pause_button")
        self.open_button = QtWidgets.QPushButton(self.tab)
        self.open_button.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.open_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("open.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_button.setIcon(icon1)
        self.open_button.setObjectName("open_button")

        self.signal_equalizer_label = QtWidgets.QLabel(self.tab)
        self.signal_equalizer_label.setGeometry(QtCore.QRect(10, 320, 101, 20))
        self.signal_equalizer_label.setObjectName("signal_equalizer_label")

        self.input_signal_label = QtWidgets.QLabel(self.tab)
        self.input_signal_label.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.input_signal_label.setObjectName("input_signal_label")

        self.verticalLayout_original = QtWidgets.QVBoxLayout()
        self.verticalLayout_original.setObjectName("verticalLayout_original")
        self.original_signal_graph = PlotWidget(self.tab)
        self.original_signal_graph.setGeometry(QtCore.QRect(20, 120, 781, 191))
        self.original_signal_graph.setObjectName("original_signal_graph")
        self.verticalLayout_original.addWidget(self.original_signal_graph)
        self.original_signal_graph.plotItem.showGrid(x=True, y=True)
        self.original_signal_graph.plotItem.setMenuEnabled(False)
        self.delete_button = QtWidgets.QPushButton(self.tab)
        self.delete_button.setGeometry(QtCore.QRect(50, 10, 31, 31))
        self.delete_button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_button.setIcon(icon6)
        self.delete_button.setObjectName("delete_button")

        self.play_button = QtWidgets.QPushButton(self.tab)
        self.play_button.setGeometry(QtCore.QRect(170, 70, 31, 31))
        self.play_button.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("play.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_button.setIcon(icon8)
        self.play_button.setObjectName("play_button")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 340, 781, 251))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 779, 249))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")

        self.slider_piano = QtWidgets.QSlider(self.scrollAreaWidgetContents_3)
        self.slider_piano.setGeometry(QtCore.QRect(20, 10, 22, 160))
        self.slider_piano.setMinimum(0)
        self.slider_piano.setMaximum(10)
        self.slider_piano.setSliderPosition(1)
        self.slider_piano.setOrientation(QtCore.Qt.Vertical)
        self.slider_piano.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_piano.setObjectName("slider_piano")

        self.slider_bongo = QtWidgets.QSlider(self.scrollAreaWidgetContents_3)
        self.slider_bongo.setGeometry(QtCore.QRect(740, 10, 22, 160))
        self.slider_bongo.setMinimum(0)
        self.slider_bongo.setMaximum(10)
        self.slider_bongo.setSliderPosition(1)
        self.slider_bongo.setOrientation(QtCore.Qt.Vertical)
        self.slider_bongo.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_bongo.setObjectName("slider_bongo")

        self.slider_drums = QtWidgets.QSlider(self.scrollAreaWidgetContents_3)
        self.slider_drums.setGeometry(QtCore.QRect(100, 10, 22, 160))
        self.slider_drums.setMinimum(0)
        self.slider_drums.setMaximum(10)
        self.slider_drums.setSliderPosition(1)
        self.slider_drums.setOrientation(QtCore.Qt.Vertical)
        self.slider_drums.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_drums.setObjectName("slider_drums")

        self.slider_guitar = QtWidgets.QSlider(self.scrollAreaWidgetContents_3)
        self.slider_guitar.setGeometry(QtCore.QRect(180, 10, 22, 160))
        self.slider_guitar.setMinimum(0)
        self.slider_guitar.setMaximum(10)
        self.slider_guitar.setSliderPosition(1)
        self.slider_guitar.setOrientation(QtCore.Qt.Vertical)
        self.slider_guitar.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_guitar.setObjectName("slider_guitar")

        self.slider_GlocKensipel = QtWidgets.QSlider(self.scrollAreaWidgetContents_3)
        self.slider_GlocKensipel.setGeometry(QtCore.QRect(500, 10, 22, 160))
        self.slider_GlocKensipel.setMinimum(0)
        self.slider_GlocKensipel.setMaximum(10)
        self.slider_GlocKensipel.setSliderPosition(1)
        self.slider_GlocKensipel.setOrientation(QtCore.Qt.Vertical)
        self.slider_GlocKensipel.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_GlocKensipel.setObjectName("slider_GlocKensipel")

        self.slider_pan_flute = QtWidgets.QSlider(self.scrollAreaWidgetContents_3)
        self.slider_pan_flute.setGeometry(QtCore.QRect(260, 10, 22, 160))
        self.slider_pan_flute.setMinimum(0)
        self.slider_pan_flute.setMaximum(10)
        self.slider_pan_flute.setSliderPosition(1)
        self.slider_pan_flute.setOrientation(QtCore.Qt.Vertical)
        self.slider_pan_flute.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_pan_flute.setObjectName("slider_pan_flute")

        self.slider_xylophone = QtWidgets.QSlider(self.scrollAreaWidgetContents_3)
        self.slider_xylophone.setGeometry(QtCore.QRect(340, 10, 22, 160))
        self.slider_xylophone.setMinimum(0)
        self.slider_xylophone.setMaximum(10)
        self.slider_xylophone.setSliderPosition(1)
        self.slider_xylophone.setOrientation(QtCore.Qt.Vertical)
        self.slider_xylophone.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_xylophone.setObjectName("slider_xylophone")

        self.slider_brass = QtWidgets.QSlider(self.scrollAreaWidgetContents_3)
        self.slider_brass.setGeometry(QtCore.QRect(420, 10, 22, 160))
        self.slider_brass.setMinimum(0)
        self.slider_brass.setMaximum(10)
        self.slider_brass.setSliderPosition(1)
        self.slider_brass.setOrientation(QtCore.Qt.Vertical)
        self.slider_brass.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_brass.setObjectName("slider_brass")

        self.slider_cymblas = QtWidgets.QSlider(self.scrollAreaWidgetContents_3)
        self.slider_cymblas.setGeometry(QtCore.QRect(580, 10, 22, 160))
        self.slider_cymblas.setMinimum(0)
        self.slider_cymblas.setMaximum(10)
        self.slider_cymblas.setSliderPosition(1)
        self.slider_cymblas.setOrientation(QtCore.Qt.Vertical)
        self.slider_cymblas.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_cymblas.setObjectName("slider_cymblas")

        self.slider_woodwind = QtWidgets.QSlider(self.scrollAreaWidgetContents_3)
        self.slider_woodwind.setGeometry(QtCore.QRect(660, 10, 22, 160))
        self.slider_woodwind.setMinimum(0)
        self.slider_woodwind.setMaximum(10)
        self.slider_woodwind.setSliderPosition(1)
        self.slider_woodwind.setOrientation(QtCore.Qt.Vertical)
        self.slider_woodwind.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_woodwind.setObjectName("slider_woodwind")

        self.piano = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.piano.setGeometry(QtCore.QRect(0, 180, 81, 61))
        self.piano.setText("")
        self.piano.setPixmap(QtGui.QPixmap("piano.jpg"))
        self.piano.setScaledContents(True)
        self.piano.setObjectName("piano")
        self.bongo = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.bongo.setGeometry(QtCore.QRect(710, 180, 61, 51))
        self.bongo.setText("")
        self.bongo.setPixmap(QtGui.QPixmap("bongo.jpeg"))
        self.bongo.setScaledContents(True)
        self.bongo.setObjectName("bongo")
        self.gituar = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.gituar.setGeometry(QtCore.QRect(160, 180, 71, 61))
        self.gituar.setText("")
        self.gituar.setPixmap(QtGui.QPixmap("giutar.jpeg"))
        self.gituar.setScaledContents(True)
        self.gituar.setObjectName("gituar")
        self.drums = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.drums.setGeometry(QtCore.QRect(90, 180, 61, 61))
        self.drums.setText("")
        self.drums.setPixmap(QtGui.QPixmap("drum.jpeg"))
        self.drums.setScaledContents(True)
        self.drums.setObjectName("drums")
        self.pan_flute = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.pan_flute.setGeometry(QtCore.QRect(240, 182, 61, 61))
        self.pan_flute.setText("")
        self.pan_flute.setPixmap(QtGui.QPixmap("pan flute.jpeg"))
        self.pan_flute.setScaledContents(True)
        self.pan_flute.setObjectName("pan_flute")
        self.xylophone = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.xylophone.setGeometry(QtCore.QRect(310, 180, 81, 61))
        self.xylophone.setText("")
        self.xylophone.setPixmap(QtGui.QPixmap("xylophone.jpeg"))
        self.xylophone.setScaledContents(True)
        self.xylophone.setObjectName("xylophone")
        self.brass = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.brass.setGeometry(QtCore.QRect(400, 180, 81, 61))
        self.brass.setText("")
        self.brass.setPixmap(QtGui.QPixmap("brass.jpeg"))
        self.brass.setScaledContents(True)
        self.brass.setObjectName("brass")
        self.Glockensipel = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.Glockensipel.setGeometry(QtCore.QRect(490, 180, 81, 61))
        self.Glockensipel.setText("")
        self.Glockensipel.setPixmap(QtGui.QPixmap("GlocKensipel.jpeg"))
        self.Glockensipel.setScaledContents(True)
        self.Glockensipel.setObjectName("Glockensipel")
        self.cymblas = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.cymblas.setGeometry(QtCore.QRect(580, 180, 61, 61))
        self.cymblas.setText("")
        self.cymblas.setPixmap(QtGui.QPixmap("cymblas.jpeg"))
        self.cymblas.setScaledContents(True)
        self.cymblas.setObjectName("cymblas")
        self.woodwind = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.woodwind.setGeometry(QtCore.QRect(650, 180, 51, 61))
        self.woodwind.setText("")
        self.woodwind.setPixmap(QtGui.QPixmap("woodwind.jpeg"))
        self.woodwind.setScaledContents(True)
        self.woodwind.setObjectName("woodwind")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)

        self.verticalLayout_spectrogram = QtWidgets.QWidget(self.tab)
        self.verticalLayout_spectrogram.setGeometry(QtCore.QRect(870, 100, 691, 280))
        self.verticalLayout_spectrogram.setObjectName("verticalLayout_spectrogram")
        self.spectogram = QtWidgets.QVBoxLayout(self.verticalLayout_spectrogram)
        self.spectogram.setContentsMargins(0, 0, 0, 0)
        self.spectogram.setObjectName("spectogram")
        self.intial_spectrogram_label = QtWidgets.QLabel(self.tab)
        self.intial_spectrogram_label.setGeometry(QtCore.QRect(870, 80, 141, 16))
        self.intial_spectrogram_label.setObjectName("intial_spectrogram_label")
        self.min_frequency_slider = QtWidgets.QSlider(self.tab)
        self.min_frequency_slider.setGeometry(QtCore.QRect(1120, 420, 241, 22))
        self.min_frequency_slider.setOrientation(QtCore.Qt.Horizontal)
        self.min_frequency_slider.setObjectName("min_frequency_slider")
        self.min_frequency_slider.setMinimum(0)
        self.min_frequency_slider.setMaximum(100)
        self.min_frequancy = QtWidgets.QLabel(self.tab)
        self.min_frequancy.setGeometry(QtCore.QRect(950, 420, 151, 16))
        self.min_frequancy.setObjectName("min_frequancy")
        self.max_frequancy = QtWidgets.QLabel(self.tab)
        self.max_frequancy.setGeometry(QtCore.QRect(950, 460, 151, 16))
        self.max_frequancy.setObjectName("max_frequancy")
        self.max_frequency_slider = QtWidgets.QSlider(self.tab)
        self.max_frequency_slider.setGeometry(QtCore.QRect(1120, 460, 241, 22))
        self.max_frequency_slider.setOrientation(QtCore.Qt.Horizontal)
        self.max_frequency_slider.setValue(100)
        self.max_frequency_slider.setMinimum(0)
        self.max_frequency_slider.setMaximum(100)
        self.max_frequency_slider.setObjectName("max_frequency_slider")
        self.control_volume_slider = QtWidgets.QSlider(self.tab)
        self.control_volume_slider.setGeometry(QtCore.QRect(410, 60, 241, 22))
        self.control_volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.control_volume_slider.setObjectName("control_volume_slider")
        self.control_volume_slider.setMinimum(0)
        self.control_volume_slider.setMaximum(100)
        self.control_volume_slider.setPageStep(10)
        self.control_volume_slider.setValue(10)
        self.music_volume_label = QtWidgets.QLabel(self.tab)
        self.music_volume_label.setGeometry(QtCore.QRect(320, 60, 81, 21))
        self.music_volume_label.setObjectName("music_volume_label")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lets_play_label = QtWidgets.QLabel(self.tab_2)
        self.lets_play_label.setGeometry(QtCore.QRect(10, 20, 121, 41))
        self.lets_play_label.setLineWidth(-26)
        self.lets_play_label.setObjectName("lets_play_label")
        self.piano_label = QtWidgets.QLabel(self.tab_2)
        self.piano_label.setGeometry(QtCore.QRect(30, 60, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.piano_label.setFont(font)
        self.piano_label.setObjectName("piano_label")
        self.drums_label = QtWidgets.QLabel(self.tab_2)
        self.drums_label.setGeometry(QtCore.QRect(30, 330, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.drums_label.setFont(font)
        self.drums_label.setObjectName("drums_label")
        self.guitar_tuner_label = QtWidgets.QLabel(self.tab_2)
        self.guitar_tuner_label.setGeometry(QtCore.QRect(30, 640, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.guitar_tuner_label.setFont(font)
        self.guitar_tuner_label.setObjectName("guitar_tuner_label")
        self.small_tom_button = QtWidgets.QPushButton(self.tab_2)
        self.small_tom_button.setGeometry(QtCore.QRect(62, 360, 101, 81))
        self.small_tom_button.setObjectName("small_tom_button")
        self.snare_drum_button = QtWidgets.QPushButton(self.tab_2)
        self.snare_drum_button.setGeometry(QtCore.QRect(62, 520, 101, 81))
        self.snare_drum_button.setObjectName("snare_drum_button")
        self.medium_tom_button = QtWidgets.QPushButton(self.tab_2)
        self.medium_tom_button.setGeometry(QtCore.QRect(390, 370, 111, 81))
        self.medium_tom_button.setObjectName("medium_tom_button")
        self.floor_tom_button = QtWidgets.QPushButton(self.tab_2)
        self.floor_tom_button.setGeometry(QtCore.QRect(390, 520, 111, 81))
        self.floor_tom_button.setObjectName("floor_tom_button")
        self.crash_cymal_button = QtWidgets.QPushButton(self.tab_2)
        self.crash_cymal_button.setGeometry(QtCore.QRect(170, 410, 93, 81))
        self.crash_cymal_button.setObjectName("crash_cymal_button")
        self.ride_cymbal_button = QtWidgets.QPushButton(self.tab_2)
        self.ride_cymbal_button.setGeometry(QtCore.QRect(290, 410, 93, 81))
        self.ride_cymbal_button.setObjectName("ride_cymbal_button")
        self.E_tune_guitar = QtWidgets.QPushButton(self.tab_2)
        self.E_tune_guitar.setGeometry(QtCore.QRect(60, 670, 93, 28))
        self.E_tune_guitar.setObjectName("E_tune_guitar")
        self.A_tune_guitar = QtWidgets.QPushButton(self.tab_2)
        self.A_tune_guitar.setGeometry(QtCore.QRect(60, 710, 93, 28))
        self.A_tune_guitar.setObjectName("A_tune_guitar")
        self.D_tune_guitar = QtWidgets.QPushButton(self.tab_2)
        self.D_tune_guitar.setGeometry(QtCore.QRect(60, 750, 93, 28))
        self.D_tune_guitar.setObjectName("D_tune_guitar")
        self.G_tune_guitar = QtWidgets.QPushButton(self.tab_2)
        self.G_tune_guitar.setGeometry(QtCore.QRect(60, 790, 93, 28))
        self.G_tune_guitar.setObjectName("G_tune_guitar")
        self.B_tune_guitar = QtWidgets.QPushButton(self.tab_2)
        self.B_tune_guitar.setGeometry(QtCore.QRect(60, 830, 93, 28))
        self.B_tune_guitar.setObjectName("B_tune_guitar")
        self.E_tune_guitar_2 = QtWidgets.QPushButton(self.tab_2)
        self.E_tune_guitar_2.setGeometry(QtCore.QRect(60, 870, 93, 28))
        self.E_tune_guitar_2.setObjectName("E_tune_guitar_2")
        self.drums_image = QtWidgets.QLabel(self.tab_2)
        self.drums_image.setGeometry(QtCore.QRect(600, 385, 291, 181))
        self.drums_image.setText("")
        self.drums_image.setPixmap(QtGui.QPixmap("drums.jpg"))
        self.drums_image.setObjectName("drums_image")
        self.hihat_button = QtWidgets.QPushButton(self.tab_2)
        self.hihat_button.setGeometry(QtCore.QRect(220, 510, 93, 81))
        self.hihat_button.setObjectName("hihat_button")
        self.guitar_tuner_image = QtWidgets.QLabel(self.tab_2)
        self.guitar_tuner_image.setGeometry(QtCore.QRect(360, 680, 311, 181))
        self.guitar_tuner_image.setText("")
        self.guitar_tuner_image.setPixmap(QtGui.QPixmap("g tuner.jpg"))
        self.guitar_tuner_image.setObjectName("guitar_tuner_image")
        self.b4 = QtWidgets.QPushButton(self.tab_2)
        self.b4.setGeometry(QtCore.QRect(280, 90, 41, 181))
        self.b4.setStyleSheet("#b4{\n"
                              "background-color: rgb(242, 242, 242);\n"
                              "background-color: qlineargradient(spread:pad, x1:1, y1:0.711, x2:0.903455, y2:0.711, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                              "}\n"
                              "\n"
                              "\n"
                              "#b4:pressed{\n"
                              "background-color: rgb(250, 250, 250);\n"
                              "\n"
                              "}")
        self.b4.setText("")
        self.b4.setObjectName("b4")
        self.g5 = QtWidgets.QPushButton(self.tab_2)
        self.g5.setGeometry(QtCore.QRect(480, 90, 41, 181))
        self.g5.setStyleSheet("#g5{\n"
                              "background-color: rgb(242, 242, 242);\n"
                              "background-color: qlineargradient(spread:pad, x1:1, y1:0.711, x2:0.903455, y2:0.711, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                              "}\n"
                              "\n"
                              "\n"
                              "#g5:pressed{\n"
                              "background-color: rgb(250, 250, 250);\n"
                              "\n"
                              "}")
        self.g5.setText("")
        self.g5.setObjectName("g5")
        self.c6 = QtWidgets.QPushButton(self.tab_2)
        self.c6.setGeometry(QtCore.QRect(600, 90, 41, 181))
        self.c6.setStyleSheet("#c6{\n"
                              "background-color: rgb(242, 242, 242);\n"
                              "background-color: qlineargradient(spread:pad, x1:1, y1:0.711, x2:0.903455, y2:0.711, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                              "}\n"
                              "\n"
                              "\n"
                              "#c6:pressed{\n"
                              "background-color: rgb(250, 250, 250);\n"
                              "\n"
                              "}")
        self.c6.setText("")
        self.c6.setObjectName("c6")
        self.f50 = QtWidgets.QPushButton(self.tab_2)
        self.f50.setGeometry(QtCore.QRect(460, 90, 31, 111))
        self.f50.setStyleSheet("#f50{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "background-color: qlineargradient(spread:pad, x1:0.028, y1:0.619, x2:1, y2:0.494, stop:0.852273 rgba(0, 0, 0, 250), stop:1 rgba(255, 255, 255, 255));\n"
                               "}\n"
                               "#f50:pressed{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "\n"
                               "    background-color: qlineargradient(spread:pad, x1:0.857955, y1:0.0170455, x2:1, y2:0, stop:0.125 rgba(0, 0, 0, 255), stop:0.977273 rgba(255, 255, 255, 255));\n"
                               "\n"
                               "}\n"
                               "")
        self.f50.setText("")
        self.f50.setObjectName("f50")
        self.c4 = QtWidgets.QPushButton(self.tab_2)
        self.c4.setGeometry(QtCore.QRect(40, 90, 41, 181))
        self.c4.setStyleSheet("#c4{\n"
                              "background-color: rgb(242, 242, 242);\n"
                              "background-color: qlineargradient(spread:pad, x1:1, y1:0.711, x2:0.903455, y2:0.711, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                              "}\n"
                              "\n"
                              "\n"
                              "#c4:pressed{\n"
                              "background-color: rgb(250, 250, 250);\n"
                              "\n"
                              "}")
        self.c4.setText("")
        self.c4.setObjectName("c4")
        self.c5 = QtWidgets.QPushButton(self.tab_2)
        self.c5.setGeometry(QtCore.QRect(320, 90, 41, 181))
        self.c5.setStyleSheet("#c5{\n"
                              "background-color: rgb(242, 242, 242);\n"
                              "background-color: qlineargradient(spread:pad, x1:1, y1:0.711, x2:0.903455, y2:0.711, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                              "}\n"
                              "\n"
                              "\n"
                              "#c5:pressed{\n"
                              "background-color: rgb(250, 250, 250);\n"
                              "\n"
                              "}")
        self.c5.setText("")
        self.c5.setObjectName("c5")
        self.d40 = QtWidgets.QPushButton(self.tab_2)
        self.d40.setGeometry(QtCore.QRect(100, 90, 31, 111))
        self.d40.setStyleSheet("#d40{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "background-color: qlineargradient(spread:pad, x1:0.028, y1:0.619, x2:1, y2:0.494, stop:0.852273 rgba(0, 0, 0, 250), stop:1 rgba(255, 255, 255, 255));\n"
                               "}\n"
                               "#d40:pressed{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "\n"
                               "    background-color: qlineargradient(spread:pad, x1:0.857955, y1:0.0170455, x2:1, y2:0, stop:0.125 rgba(0, 0, 0, 255), stop:0.977273 rgba(255, 255, 255, 255));\n"
                               "\n"
                               "}\n"
                               "")
        self.d40.setText("")
        self.d40.setObjectName("d40")
        self.c50 = QtWidgets.QPushButton(self.tab_2)
        self.c50.setGeometry(QtCore.QRect(340, 90, 31, 111))
        self.c50.setStyleSheet("#c50{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "background-color: qlineargradient(spread:pad, x1:0.028, y1:0.619, x2:1, y2:0.494, stop:0.852273 rgba(0, 0, 0, 250), stop:1 rgba(255, 255, 255, 255));\n"
                               "}\n"
                               "#c50:pressed{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "\n"
                               "    background-color: qlineargradient(spread:pad, x1:0.857955, y1:0.0170455, x2:1, y2:0, stop:0.125 rgba(0, 0, 0, 255), stop:0.977273 rgba(255, 255, 255, 255));\n"
                               "\n"
                               "}\n"
                               "")
        self.c50.setText("")
        self.c50.setObjectName("c50")
        self.d4 = QtWidgets.QPushButton(self.tab_2)
        self.d4.setGeometry(QtCore.QRect(80, 90, 41, 181))
        self.d4.setStyleSheet("#d4{\n"
                              "background-color: rgb(242, 242, 242);\n"
                              "background-color: qlineargradient(spread:pad, x1:1, y1:0.711, x2:0.903455, y2:0.711, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                              "}\n"
                              "\n"
                              "\n"
                              "#d4:pressed{\n"
                              "background-color: rgb(250, 250, 250);\n"
                              "\n"
                              "}")
        self.d4.setText("")
        self.d4.setObjectName("d4")
        self.g4 = QtWidgets.QPushButton(self.tab_2)
        self.g4.setGeometry(QtCore.QRect(200, 90, 41, 181))
        self.g4.setStyleSheet("#g4{\n"
                              "background-color: rgb(242, 242, 242);\n"
                              "background-color: qlineargradient(spread:pad, x1:1, y1:0.711, x2:0.903455, y2:0.711, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                              "}\n"
                              "\n"
                              "\n"
                              "#g4:pressed{\n"
                              "background-color: rgb(250, 250, 250);\n"
                              "\n"
                              "}")
        self.g4.setText("")
        self.g4.setObjectName("g4")
        self.a40 = QtWidgets.QPushButton(self.tab_2)
        self.a40.setGeometry(QtCore.QRect(260, 90, 31, 111))
        self.a40.setStyleSheet("#a40{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "background-color: qlineargradient(spread:pad, x1:0.028, y1:0.619, x2:1, y2:0.494, stop:0.852273 rgba(0, 0, 0, 250), stop:1 rgba(255, 255, 255, 255));\n"
                               "}\n"
                               "#a40:pressed{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "\n"
                               "    background-color: qlineargradient(spread:pad, x1:0.857955, y1:0.0170455, x2:1, y2:0, stop:0.125 rgba(0, 0, 0, 255), stop:0.977273 rgba(255, 255, 255, 255));\n"
                               "\n"
                               "}\n"
                               "")
        self.a40.setText("")
        self.a40.setObjectName("a40")
        self.c40 = QtWidgets.QPushButton(self.tab_2)
        self.c40.setGeometry(QtCore.QRect(60, 90, 31, 111))
        self.c40.setStyleSheet("#c40{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "background-color: qlineargradient(spread:pad, x1:0.028, y1:0.619, x2:1, y2:0.494, stop:0.852273 rgba(0, 0, 0, 250), stop:1 rgba(255, 255, 255, 255));\n"
                               "}\n"
                               "#c40:pressed{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "\n"
                               "    background-color: qlineargradient(spread:pad, x1:0.857955, y1:0.0170455, x2:1, y2:0, stop:0.125 rgba(0, 0, 0, 255), stop:0.977273 rgba(255, 255, 255, 255));\n"
                               "\n"
                               "}\n"
                               "")
        self.c40.setText("")
        self.c40.setObjectName("c40")
        self.a4 = QtWidgets.QPushButton(self.tab_2)
        self.a4.setGeometry(QtCore.QRect(240, 90, 41, 181))
        self.a4.setStyleSheet("#a4{\n"
                              "background-color: rgb(242, 242, 242);\n"
                              "background-color: qlineargradient(spread:pad, x1:1, y1:0.711, x2:0.903455, y2:0.711, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                              "}\n"
                              "\n"
                              "\n"
                              "#a4:pressed{\n"
                              "background-color: rgb(250, 250, 250);\n"
                              "\n"
                              "}")
        self.a4.setText("")
        self.a4.setObjectName("a4")
        self.e4 = QtWidgets.QPushButton(self.tab_2)
        self.e4.setGeometry(QtCore.QRect(120, 90, 41, 181))
        self.e4.setStyleSheet("#e4{\n"
                              "background-color: rgb(242, 242, 242);\n"
                              "background-color: qlineargradient(spread:pad, x1:1, y1:0.711, x2:0.903455, y2:0.711, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                              "}\n"
                              "\n"
                              "\n"
                              "#e4:pressed{\n"
                              "background-color: rgb(250, 250, 250);\n"
                              "\n"
                              "}")
        self.e4.setText("")
        self.e4.setObjectName("e4")
        self.d5 = QtWidgets.QPushButton(self.tab_2)
        self.d5.setGeometry(QtCore.QRect(360, 90, 41, 181))
        self.d5.setStyleSheet("#d5{\n"
                              "background-color: rgb(242, 242, 242);\n"
                              "background-color: qlineargradient(spread:pad, x1:1, y1:0.711, x2:0.903455, y2:0.711, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                              "}\n"
                              "\n"
                              "\n"
                              "#d5:pressed{\n"
                              "background-color: rgb(250, 250, 250);\n"
                              "\n"
                              "}")
        self.d5.setText("")
        self.d5.setObjectName("d5")
        self.d50 = QtWidgets.QPushButton(self.tab_2)
        self.d50.setGeometry(QtCore.QRect(380, 90, 31, 111))
        self.d50.setStyleSheet("#d50{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "background-color: qlineargradient(spread:pad, x1:0.028, y1:0.619, x2:1, y2:0.494, stop:0.852273 rgba(0, 0, 0, 250), stop:1 rgba(255, 255, 255, 255));\n"
                               "}\n"
                               "#d50:pressed{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "\n"
                               "    background-color: qlineargradient(spread:pad, x1:0.857955, y1:0.0170455, x2:1, y2:0, stop:0.125 rgba(0, 0, 0, 255), stop:0.977273 rgba(255, 255, 255, 255));\n"
                               "\n"
                               "}\n"
                               "")
        self.d50.setText("")
        self.d50.setObjectName("d50")
        self.e5 = QtWidgets.QPushButton(self.tab_2)
        self.e5.setGeometry(QtCore.QRect(400, 90, 41, 181))
        self.e5.setStyleSheet("#e5{\n"
                              "background-color: rgb(242, 242, 242);\n"
                              "background-color: qlineargradient(spread:pad, x1:1, y1:0.711, x2:0.903455, y2:0.711, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                              "}\n"
                              "\n"
                              "\n"
                              "#e5:pressed{\n"
                              "background-color: rgb(250, 250, 250);\n"
                              "\n"
                              "}")
        self.e5.setText("")
        self.e5.setObjectName("e5")
        self.f4 = QtWidgets.QPushButton(self.tab_2)
        self.f4.setGeometry(QtCore.QRect(160, 90, 41, 181))
        self.f4.setStyleSheet("#f4{\n"
                              "background-color: rgb(242, 242, 242);\n"
                              "background-color: qlineargradient(spread:pad, x1:1, y1:0.711, x2:0.903455, y2:0.711, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                              "}\n"
                              "\n"
                              "\n"
                              "#f4:pressed{\n"
                              "background-color: rgb(250, 250, 250);\n"
                              "\n"
                              "}")
        self.f4.setText("")
        self.f4.setObjectName("f4")
        self.f5 = QtWidgets.QPushButton(self.tab_2)
        self.f5.setGeometry(QtCore.QRect(440, 90, 41, 181))
        self.f5.setStyleSheet("#f5{\n"
                              "background-color: rgb(242, 242, 242);\n"
                              "background-color: qlineargradient(spread:pad, x1:1, y1:0.711, x2:0.903455, y2:0.711, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                              "}\n"
                              "\n"
                              "\n"
                              "#f5:pressed{\n"
                              "background-color: rgb(250, 250, 250);\n"
                              "\n"
                              "}")
        self.f5.setText("")
        self.f5.setObjectName("f5")
        self.g50 = QtWidgets.QPushButton(self.tab_2)
        self.g50.setGeometry(QtCore.QRect(500, 90, 31, 111))
        self.g50.setStyleSheet("#g50{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "background-color: qlineargradient(spread:pad, x1:0.028, y1:0.619, x2:1, y2:0.494, stop:0.852273 rgba(0, 0, 0, 250), stop:1 rgba(255, 255, 255, 255));\n"
                               "}\n"
                               "#g50:pressed{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "\n"
                               "    background-color: qlineargradient(spread:pad, x1:0.857955, y1:0.0170455, x2:1, y2:0, stop:0.125 rgba(0, 0, 0, 255), stop:0.977273 rgba(255, 255, 255, 255));\n"
                               "\n"
                               "}\n"
                               "")
        self.g50.setText("")
        self.g50.setObjectName("g50")
        self.f40 = QtWidgets.QPushButton(self.tab_2)
        self.f40.setGeometry(QtCore.QRect(180, 90, 31, 111))
        self.f40.setStyleSheet("#f40{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "background-color: qlineargradient(spread:pad, x1:0.028, y1:0.619, x2:1, y2:0.494, stop:0.852273 rgba(0, 0, 0, 250), stop:1 rgba(255, 255, 255, 255));\n"
                               "}\n"
                               "#f40:pressed{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "\n"
                               "    background-color: qlineargradient(spread:pad, x1:0.857955, y1:0.0170455, x2:1, y2:0, stop:0.125 rgba(0, 0, 0, 255), stop:0.977273 rgba(255, 255, 255, 255));\n"
                               "\n"
                               "}\n"
                               "")
        self.f40.setText("")
        self.f40.setObjectName("f40")
        self.a50 = QtWidgets.QPushButton(self.tab_2)
        self.a50.setGeometry(QtCore.QRect(540, 90, 31, 111))
        self.a50.setStyleSheet("#a50{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "background-color: qlineargradient(spread:pad, x1:0.028, y1:0.619, x2:1, y2:0.494, stop:0.852273 rgba(0, 0, 0, 250), stop:1 rgba(255, 255, 255, 255));\n"
                               "}\n"
                               "#a50:pressed{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "\n"
                               "    background-color: qlineargradient(spread:pad, x1:0.857955, y1:0.0170455, x2:1, y2:0, stop:0.125 rgba(0, 0, 0, 255), stop:0.977273 rgba(255, 255, 255, 255));\n"
                               "\n"
                               "}\n"
                               "")
        self.a50.setText("")
        self.a50.setObjectName("a50")
        self.b5 = QtWidgets.QPushButton(self.tab_2)
        self.b5.setGeometry(QtCore.QRect(560, 90, 41, 181))
        self.b5.setStyleSheet("#b5{\n"
                              "background-color: rgb(242, 242, 242);\n"
                              "background-color: qlineargradient(spread:pad, x1:1, y1:0.711, x2:0.903455, y2:0.711, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                              "}\n"
                              "\n"
                              "\n"
                              "#b5:pressed{\n"
                              "background-color: rgb(250, 250, 250);\n"
                              "\n"
                              "}")
        self.b5.setText("")
        self.b5.setObjectName("b5")
        self.g40 = QtWidgets.QPushButton(self.tab_2)
        self.g40.setGeometry(QtCore.QRect(220, 90, 31, 111))
        self.g40.setStyleSheet("#g40{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "background-color: qlineargradient(spread:pad, x1:0.028, y1:0.619, x2:1, y2:0.494, stop:0.852273 rgba(0, 0, 0, 250), stop:1 rgba(255, 255, 255, 255));\n"
                               "}\n"
                               "#g40:pressed{\n"
                               "background-color: rgb(0, 0, 0);\n"
                               "\n"
                               "    background-color: qlineargradient(spread:pad, x1:0.857955, y1:0.0170455, x2:1, y2:0, stop:0.125 rgba(0, 0, 0, 255), stop:0.977273 rgba(255, 255, 255, 255));\n"
                               "\n"
                               "}\n"
                               "")
        self.g40.setText("")
        self.g40.setObjectName("g40")
        self.a5 = QtWidgets.QPushButton(self.tab_2)
        self.a5.setGeometry(QtCore.QRect(520, 90, 41, 181))
        self.a5.setStyleSheet("#a5{\n"
                              "background-color: rgb(242, 242, 242);\n"
                              "background-color: qlineargradient(spread:pad, x1:1, y1:0.711, x2:0.903455, y2:0.711, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
                              "}\n"
                              "\n"
                              "\n"
                              "#a5:pressed{\n"
                              "background-color: rgb(250, 250, 250);\n"
                              "\n"
                              "}")
        self.a5.setText("")
        self.a5.setObjectName("a5")

        self.d4.raise_()
        self.b4.raise_()
        self.g5.raise_()
        self.c6.raise_()
        self.c4.raise_()
        self.c5.raise_()
        self.g4.raise_()
        self.c40.raise_()
        self.a4.raise_()
        self.e4.raise_()
        self.d5.raise_()
        self.e5.raise_()
        self.f4.raise_()
        self.f5.raise_()
        self.f40.raise_()
        self.b5.raise_()
        self.g40.raise_()
        self.a5.raise_()
        self.d40.raise_()
        self.a40.raise_()
        self.c50.raise_()
        self.d50.raise_()
        self.f50.raise_()
        self.g50.raise_()
        self.a50.raise_()
        self.player = QMediaPlayer()
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # These are white keys
        self.c4.clicked.connect(self.run_threads_piano)
        self.d4.clicked.connect(self.run_threads_piano)
        self.e4.clicked.connect(self.run_threads_piano)
        self.f4.clicked.connect(self.run_threads_piano)
        self.g4.clicked.connect(self.run_threads_piano)
        self.a4.clicked.connect(self.run_threads_piano)
        self.b4.clicked.connect(self.run_threads_piano)
        self.c5.clicked.connect(self.run_threads_piano)
        self.d5.clicked.connect(self.run_threads_piano)
        self.e5.clicked.connect(self.run_threads_piano)
        self.f5.clicked.connect(self.run_threads_piano)
        self.g5.clicked.connect(self.run_threads_piano)
        self.a5.clicked.connect(self.run_threads_piano)
        self.b5.clicked.connect(self.run_threads_piano)
        self.c6.clicked.connect(self.run_threads_piano)

        # These are the black keys
        self.c40.clicked.connect(self.run_threads_piano)
        self.c50.clicked.connect(self.run_threads_piano)
        self.d40.clicked.connect(self.run_threads_piano)
        self.d50.clicked.connect(self.run_threads_piano)
        self.f40.clicked.connect(self.run_threads_piano)
        self.f50.clicked.connect(self.run_threads_piano)
        self.g40.clicked.connect(self.run_threads_piano)
        self.g50.clicked.connect(self.run_threads_piano)
        self.a40.clicked.connect(self.run_threads_piano)
        self.a50.clicked.connect(self.run_threads_piano)

        # These are the guitar keys
        self.E_tune_guitar.clicked.connect(self.run_threads)
        self.E_tune_guitar_2.clicked.connect(self.run_threads)
        self.A_tune_guitar.clicked.connect(self.run_threads)
        self.D_tune_guitar.clicked.connect(self.run_threads)
        self.G_tune_guitar.clicked.connect(self.run_threads)
        self.B_tune_guitar.clicked.connect(self.run_threads)

        # Drum Keys
        self.small_tom_button.clicked.connect(self.run_threads)
        self.snare_drum_button.clicked.connect(self.run_threads)
        self.medium_tom_button.clicked.connect(self.run_threads)
        self.floor_tom_button.clicked.connect(self.run_threads)
        self.crash_cymal_button.clicked.connect(self.run_threads)
        self.ride_cymbal_button.clicked.connect(self.run_threads)
        self.hihat_button.clicked.connect(self.run_threads)

        # action the buttons

        self.open_button.clicked.connect(lambda: self.openWAVfile())
        self.delete_button.clicked.connect(lambda: self.clear())
        self.play_button.clicked.connect(lambda: self.play())
        self.pause_button.clicked.connect(lambda: self.pause())
        self.min_frequency_slider.valueChanged.connect(lambda: self.spectro_slider())
        self.max_frequency_slider.valueChanged.connect(lambda: self.spectro_slider())
        self.control_volume_slider.valueChanged.connect(lambda: self.volume_change())
        self.player = QMediaPlayer()
        self.player.setVolume(25)

        self.threads_array = {}
        self.threads_piano = {}

        self.cmap = None
        self.specdata = []
        self.pen1 = pg.mkPen((0, 255, 0))
        self.pen2 = pg.mkPen((0, 0, 255))
        self.timer = QtCore.QTimer()
        self.timer2 = QtCore.QTimer()
        self.new = []
        self.sliders = [self.slider_piano, self.slider_bongo, self.slider_drums,
                        self.slider_guitar, self.slider_GlocKensipel, self.slider_pan_flute,
                        self.slider_xylophone, self.slider_brass, self.slider_cymblas,
                        self.slider_woodwind]

        # #Configure each slider
        for i in range(10):
            self.sliders[i].valueChanged.connect(lambda: self.gain(i))

    def openWAVfile(self):
        self.original_signal_graph.clear()
        options = QFileDialog.Options()
        self.filename, _ = QFileDialog.getOpenFileName(None, "Open File", "*.WAV", options=options)
        with contextlib.closing(wave.open(self.filename, 'r')) as f:
            self.frames = f.getnframes()
            self.rate = f.getframerate()
            duration = self.frames / float(self.rate)
        self.samplingfrequency, self.signalData = wavfile.read(self.filename)
        url= QtCore.QUrl.fromLocalFile(self.filename)
        self.time = np.arange(0, duration, 1 / self.samplingfrequency)
        self.data_line1 = self.original_signal_graph.plot(self.time, self.signalData, pen=self.pen2)
        self.original_signal_graph.plotItem.setLimits(xMin=0, xMax=1, yMin=-500, yMax=500)
        self.idx1 = 0
        self.timer.setInterval(10)
        self.timer.timeout.connect(self.update_plot_data1)
        self.timer.start()
        self.bands()
        self.specdata = self.signalData
        self.fft(self.signalData)
        self.minvalue = 0
        self.maxvalue = self.freq_max
        self.showspectrogram()
        self.content = QMediaContent(url)
        self.player.setMedia(self.content)
        self.player.play()
        #sd.play(self.signalData)
    def update_plot_data1(self):
        x_axis = self.time[:self.idx1]
        y_axis = self.signalData[:self.idx1]
        self.idx1 += 10
        if self.idx1 > len(self.time):
            self.idx1 = 0
        if self.time[self.idx1] > 0.5:
            self.original_signal_graph.setLimits(xMin=min(x_axis, default=0), xMax=max(x_axis, default=0))  # disable paning over xlimits
        self.original_signal_graph.plotItem.setXRange(max(x_axis, default=0) - 0.5, max(x_axis, default=0))
        self.data_line1.setData(x_axis, y_axis)
        self.player.play()

    def fft(self, signal):
        self.yfrequancy_signal = fft(signal)
        self.xfrequancy_signal = fftfreq(self.frames, 1 / self.samplingfrequency)
        self.freq_max = max(self.xfrequancy_signal)

    def showspectrogram(self):
        plt.specgram(self.specdata, Fs=self.samplingfrequency, cmap="plasma")
        plt.ylim(self.minvalue, self.maxvalue)
        plt.savefig('image.png')
        self.pixmap = QPixmap('image.png')
        self.pixmap = self.pixmap.scaled(600, 300)
        self.label = QLabel()
        self.label.setPixmap(self.pixmap)
        self.label.setFixedSize(600, 300)
        self.spectogram.addWidget(self.label)
        self.spectogram.removeWidget(self.label)

    def spectro_slider(self):
        self.minvalue = (float(self.min_frequency_slider.value()) / 100) * self.freq_max
        self.maxvalue = (float(self.max_frequency_slider.value()) / 100) * self.freq_max
        self.new.clear()
        for x in range(len(self.xfrequancy_signal)):
            if (self.xfrequancy_signal[x] > self.minvalue) and (self.xfrequancy_signal[x] < self.maxvalue):
                self.new.append(self.yfrequancy_signal[x])
            else:
                self.new.append(0)
        self.newphase = np.angle(self.new)
        self.specdata = np.real(ifft(np.multiply(np.array(self.new), np.exp(1j * self.newphase))))
        self.showspectrogram()

    def recover_signal(self):
        self.original_signal_graph.clear()
        self.recovered_signal = ifft(np.multiply(np.array(self.ouputsignaldata), np.exp(1j * self.phase)))
        self.data_line2 = self.original_signal_graph.plot(self.time, np.real(self.recovered_signal), pen=self.pen1)
        self.original_signal_graph.plotItem.setLimits(xMin=0, xMax=1, yMin=-500, yMax=500)
        self.idx1 = 0
        self.timer.setInterval(10)
        self.timer.timeout.connect(self.update_plot_data2)
        self.timer.start()

        recover = np.array(self.recovered_signal)
        self.fft(recover)
        self.player.pause()
        sd.play(np.real(self.recovered_signal))
        self.specdata = np.real(recover)
        self.showspectrogram()

    def update_plot_data2(self):
        x_axis = self.time[:self.idx1]
        y_axis = self.signalData[:self.idx1]
        self.idx1 += 10
        if self.idx1> len(self.time):
            self.idx1 = 0

        if self.time[self.idx1] > 0.5:
            self.original_signal_graph.setLimits(xMin=min(x_axis, default=0), xMax=max(x_axis, default=0))  # disable paning over xlimits
        self.original_signal_graph.plotItem.setXRange(max(x_axis, default=0) - 0.5, max(x_axis, default=0))

        self.data_line2.setData(x_axis, y_axis)
    def bands(self):
        self.bands_list = []
        self.yfrequancy_banda = fft(self.signalData)
        self.mag = np.abs(self.yfrequancy_banda)
        self.phase = np.angle(self.yfrequancy_banda)
        BW = math.ceil(len(self.yfrequancy_banda) / 10)
        for i in range(10):
            self.bands_list.append(self.mag[i * BW:(i + 1) * BW])
        self.recovered_bands = self.bands_list.copy()
    def gain(self, i):
        self.ouputsignaldata = []
        for i in range(10):
            self.recovered_bands[i] = self.bands_list[i] * self.sliders[i].value()
        for sublist in self.recovered_bands:
            for x in sublist:
                self.ouputsignaldata.append(x)
        self.recover_signal()
    #def volume (self,num):

    def play(self):
        self.player.play()
        self.timer.start()
        sd.stop()
    def pause (self):
        self.player.pause()
        self.timer.stop()
        sd.stop()

    def clear (self):
        self.original_signal_graph.clear()
        self.player.stop()
    def Play_notes(self, notePath):
       playsound.playsound(notePath, block=True)
       print(notePath)
    def Play_notes_piano(self, notePath):
       playsound.playsound(notePath, block=False)
       print(notePath)
    def run_threads(self):
       self.threads_array[self.mw.sender().objectName()] = Thread(target=self.Play_notes, args=(
        'Sounds/' + '{}.wav'.format(self.mw.sender().objectName()),))
       self.threads_array[self.mw.sender().objectName()].start()
       self.threads_array[self.mw.sender().objectName()].join()

    def run_threads_piano(self):
       self.threads_piano[self.mw.sender().objectName()] = Thread(target=self.Play_notes_piano, args=(
        'Sounds/' + '{}.wav'.format(self.mw.sender().objectName()),))
       self.threads_piano[self.mw.sender().objectName()].start()
       self.threads_piano[self.mw.sender().objectName()].join()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pause_button.setShortcut(_translate("MainWindow", "Ctrl+X, Ctrl+1"))
        self.open_button.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.signal_equalizer_label.setText(_translate("MainWindow", "Signal Equalizer"))
        self.delete_button.setShortcut(_translate("MainWindow", "Esc"))
        self.play_button.setShortcut(_translate("MainWindow", "Ctrl+Z, Ctrl+1"))
        self.intial_spectrogram_label.setText(_translate("MainWindow", "Initial Spectrogram"))
        self.max_frequancy.setText(_translate("MainWindow", "Set Maximum Frequency"))
        self.min_frequancy.setText(_translate("MainWindow", "Set Minumum Frequency"))
        self.music_volume_label.setText(_translate("MainWindow", "Music volume"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.lets_play_label.setText(_translate("MainWindow", "Let\'s play music"))
        self.piano_label.setText(_translate("MainWindow", "Piano "))
        self.drums_label.setText(_translate("MainWindow", "Drums "))
        self.guitar_tuner_label.setText(_translate("MainWindow", "Guitar Tuner"))
        self.small_tom_button.setText(_translate("MainWindow", "Small Tom"))
        self.snare_drum_button.setText(_translate("MainWindow", "Snare Drum"))
        self.medium_tom_button.setText(_translate("MainWindow", "Medium Tom"))
        self.floor_tom_button.setText(_translate("MainWindow", "Floor Tom "))
        self.crash_cymal_button.setText(_translate("MainWindow", "Crash Cymbal"))
        self.ride_cymbal_button.setText(_translate("MainWindow", "Ride Cymbal"))
        self.E_tune_guitar.setText(_translate("MainWindow", "E"))
        self.A_tune_guitar.setText(_translate("MainWindow", "A"))
        self.D_tune_guitar.setText(_translate("MainWindow", "D"))
        self.G_tune_guitar.setText(_translate("MainWindow", "G"))
        self.B_tune_guitar.setText(_translate("MainWindow", "B"))
        self.E_tune_guitar_2.setText(_translate("MainWindow", "E"))
        self.hihat_button.setText(_translate("MainWindow", "Hi-Hat "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
